// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBu919P6fXDr7YibmopJcEV4xKMh7l_GZ8',
    appId: '1:1029957735829:web:210fa43c38d3a3f8ab129c',
    messagingSenderId: '1029957735829',
    projectId: 'w4-catalog',
    authDomain: 'w4-catalog.firebaseapp.com',
    storageBucket: 'w4-catalog.firebasestorage.app',
    measurementId: 'G-KMJHERFDZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1QICOJauHdO0Nk9icO_b5vezneeoybSc',
    appId: '1:1029957735829:android:b2a2ba36c9ef2ec3ab129c',
    messagingSenderId: '1029957735829',
    projectId: 'w4-catalog',
    storageBucket: 'w4-catalog.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQ8nyeaJo2deYbMUJBtxMhYo5v1h9Zzx0',
    appId: '1:1029957735829:ios:1863028f410db3aaab129c',
    messagingSenderId: '1029957735829',
    projectId: 'w4-catalog',
    storageBucket: 'w4-catalog.firebasestorage.app',
    androidClientId: '1029957735829-5k884u79es85fearjrpnsbnlb7s1mq01.apps.googleusercontent.com',
    iosClientId: '1029957735829-889un6qki7modem8lmegmaeevodmot74.apps.googleusercontent.com',
    iosBundleId: 'com.example.pasarMalam',
  );

}